/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "Welcome to": "欢迎来到",
    "Stats": "统计",
    "luck": "幸运",
    "Reduces cooldown": "减少冷却时间",
    "Store": "商店",
    "We reward": "我们奖励",
    "Great!": "太棒了!",
    "Game of Chance": "概率游戏",
    "Formulas": "公式",
    "Flip": "翻转",
    "Events": "事件",
    "Buy new coin": "购买新硬币",
    "Balance": "余额",
    "Add another coin.": "增加另一个硬币。",
    "A Game of Chance": "一个关于概率的游戏。",
    ", an absolutely penguin-free game. Most games reward skill, strategy and countless hours of practice... but here?": "这是一款绝对不含企鹅的游戏。大多数游戏都会奖励技能、策略和无数小时的练习……但是在这里呢？",
    "Greetings, future Probability Wizard!": "你好，未来的概率魔法师！",
    "In this game, we embark on a journey to witness the extraordinary. The rarer the event, the sweeter the reward. Let's get started!": "在这个游戏中，我们将踏上一段见证非凡之事的旅程。事件越罕见，奖励就越丰厚。让我们开始吧！",
    ". It has potential. Dreams. A": "它蕴藏着潜力，承载着梦想。",
    "\"Just a coin?\" you might say. But this isn't ANY coin. This is a": "“只是一枚硬币而已？”你或许会这么想。但这绝非普通的硬币。这是一个 ——",
    "(Developer note: It won't. A physics engine is too hard to implement.)": "（开发人员备注：做不到的。物理引擎太难实现了。）",
    "Behold! A": "请看！一个",
    "chance of being heads, and a": "它有正面朝上的概率，",
    "chance of disappointing you by being tails.": "也有让你失望的反面朝上概率。",
    "Click the button to flip it! Each flip is a journey into the unknown. Will it be heads? Will it be tails? Will it somehow land on its edge and defy physics?": "点击按钮抛掷它！每一次翻转，都是一场通往未知的旅程。会是正面？会是反面？还是会奇迹般地立在边缘，违背物理法则？",
    "COIN": "硬币",
    "Digital Probability Disc™": "数字概率盘",
    "Not impressed.": "没什么可惊艳的。",
    "chance =": "几率 =",
    "It's like a": "它就像一个",
    "Let's do it!": "让我们开始吧！",
    "Let's play!": "开始玩吧！",
    "lucky": "幸运",
    "math": "数学",
    "or": "或",
    "Results": "结果",
    "secret": "秘密",
    "Total: +": "总计: +",
    "UNLOCKED": "已解锁",
    "You did it!": "你做到了！",
    "You got": "你得到了",
    "You just need to be": "你只需要做到",
    "Great": "太棒了",
    "Got it!": "知道了！",
    "Flipping": "翻转中",
    "bigger": "大于",
    "At Least": "至少",
    "You survived the tutorial!": "你完成了教程！",
    "everything": "所有",
    "Extra Info": "附加信息",
    "fake internet money": "虚假网络货币",
    "feel smart": "感觉聪明",
    "Coin Value Boost": "硬币价值提升",
    "Message Template": "消息模板",
    "So... you understood": "所以……你明白了",
    "Increases value by x1.1 (stacks with previous boosts)": "增加价值 x1.1（与之前的增益叠加）",
    "How it works": "工作原理",
    "— 100% certainty. Even a rock could do it.": "——百分之百的确定性。就算是石头也能做到。",
    ", except you can't lose your life savings and nobody will stage an intervention!": "，只不过你不会因为搞砸这件事而失去毕生积蓄，而且也不会有人来干预阻止你！",
    ", you don't actually need to understand any of that math to be good at this game.": "，你其实根本不需要懂那些数学知识就能在这项游戏中表现出色。",
    "! Chase those events like they owe you money! Make those numbers get": "!像对待欠你钱的人那样去应对那些事情！让那些数字变得（变得）更好！",
    "! The formulas are just there to make you": "!这些公式的存在只是为了让你.......",
    ". This is often more useful than exact counts for determining 'success'.": "。这通常比精确的计数更有助于确定“成功”的程度。",
    "\"At least x heads in n coins\"": "“在 n 枚硬币中至少出现 x 次正面”",
    "According to our formula, you have been paid": "根据我们的公式，您已获得报酬",
    "An event's likelihood equals how much it generates:": "一个事件发生的可能性等于其产生的价值：",
    "Binomial distribution": "二项分布",
    "But maybe you expected more of this game? What if I told you that you could win": "但也许您期望这个游戏能有更高的胜算？如果我告诉您，您有可能获胜",
    "Calculates the probability of getting at least a certain number of heads, based on the": "根据一定的条件计算出至少获得一定数量正面的概率，基于",
    "for the trivially true": "对于显然成立的情况",
    "Good luck out there!": "祝您好运！",
    "Great, I understood everything": "太好了，我都明白了",
    "in exchange for looking at some": "交换条件是看一些",
    "Let's take a look at your first formula!": "让我们来看看你的第一个公式！",
    "likely •": "可能•",
    "mathematical safari": "数学探险",
    "Remember: The rarer the event, the sweeter the reward! Hunt those probabilities like a": "请记住：事件越罕见，奖励就越丰厚！像狩猎概率一样去寻找那些概率吧！",
    "Tails": "尾巴",
    "That's what they all say! But here's a little": "这就是他们所说的全部内容！但这里还有一个小知识点：",
    "The Majority Rule": "多数原则",
    "The minimum number of heads required": "所需的最少硬币数量",
    "The number of heads obtained": "实际获得的硬币数量",
    "The probability of getting at least 50% heads is always slightly more than 50% because it includes the exact 50/50 case.": "获得至少 50% 硬币正面朝上的概率总是略高于 50%，这是因为它包含了恰好 50/50 的情况。",
    "Thrilling!": "惊心动魄！",
    "Total number of coins flipped": "总共翻动的硬币数量",
    "Try to flip the coin to earn your first coins.": "试着翻动硬币以获得你的第一枚硬币。",
    "Unlock powerful coin formulas to earn more money.": "解锁强大的硬币公式以赚取更多金钱。",
    "Variables": "变量",
    "while the random number generator does all the work. It's the academic equivalent of nodding while the teacher talks.": "而随机数生成器则完成了所有的工作。这在学术界就相当于老师讲课时你只是点头附和而已。",
    "You are now a certified Probability Apprentice.": "你现在已成为一名正式的概率学徒了。",
    "Unlock powerful coin formulas to earn more money.": "解锁强大的金币公式以赚取更多金钱。",
    "Unlock map": "解锁地图",
    "New Games": "新游戏",
    "Boost: x": "提升: x",
    "Auto-Flip (Basic)": "自动翻转 (基础)",
    "Darts": "飞镖",
    "Discover a purple event": "发现一个紫色事件",
    "Discover unique blue events": "发现一个独特的蓝色事件",
    "/ action": "/ 动作",
    "📊 Overview": "📊 概览",
    "Coins": "硬币",
    "Coin": "硬币",
    "coin": "硬币",
    "Blue": "蓝色",
    "Best": "最佳",
    "Action": "动作",
    "Common": "普通",
    "Common Events": "普通事件",
    "Currency Spent": "花费货币",
    "Currency Earned": "赚取货币",
    "Earned": "已赚取",
    "Earnings": "赚取",
    "Efficiency": "效率",
    "Efficiency Score": "效率分数",
    "General": "常规",
    "Formulas (": "公式 (",
    "Formula History": "公式历史",
    "Formulas Unlocked": "已解锁公式",
    "Last 10 actions": "最近 10 动作",
    "Lv.": "等级",
    "Playtime": "游戏时长",
    "Purchases": "购买",
    "s Owned": "已拥有",
    "Spent": "花费",
    "Unique": "独特",
    "Unlocked": "已解锁",
    "Total": "总计",
    "Total Actions": "总计动作",
    "Total Events": "总计事件",
    "Total Flip All Actions": "所有动作总计翻转",
    "Total Items Flipped": "总计翻转的物品",
    "Total Coins Flipped": "总计硬币翻转",
    "Value Boost Level": "价值提升等级",
    "... having O-Negative blood.": "...有o型阴性血。",
    "... having blue eyes.": "...有蓝色眼睛。",
    "... getting a blackjack (first two cards).": "...得到一个21点（前两张牌）。",
    "\"At least x heads in a row in n coins\"": "“在 n 枚硬币中，至少连续出现 x 次正面朝上”",
    "Global Stats": "全局统计",
    "Global Statistics": "全局统计",
    "Got it": "知道了",
    "\"Exactly x heads in n coins\"": "\“n枚硬币中正好有x个正面\”",
    "🏆 Top 3 Most Unlikely Events Discovered": "🏆发现的最不可能的3个事件",
    "Activity": "活动",
    "Best Flip All Action": "最佳翻转全动作",
    "Calculates the exact probability of getting a specific number of heads. This is the foundation of the": "这是计算找到至少长度为 x 的连续正面朝上的概率的基础。这使用了通用的",
    "Calculates the probability of finding a consecutive run of heads of at least length x. This uses a generalized": "计算找到连续出现至少长度为x的正面的概率",
    "Chance of getting at least x heads in a row": "连续得到至少x次正面的概率",
    "Chance of getting at least x heads in n coins": "n枚硬币中至少得到x次正面的概率",
    "Chance of getting exactly x heads in n coins": "n枚硬币中恰好得到x个正面的概率",
    "Combined progress across all game modes": "综合所有游戏模式的进度",
    "Discover a purple event": "发现一个紫色事件",
    "Discover unique blue events": "发现独特的蓝色事件",
    "Even if you expect 5 heads in 10 flips, the chance of getting exactly 5 is only about 24.6%!": "即使你期望在10次投掷中得到5次正面，恰好得到5次正面的几率也只有24.6%！",
    "Exact Count": "精确计数",
    "Fibonacci sequence": "斐波那契数列",
    "for exact calculation.": "为了精确计算。",
    "getting a blackjack (first two cards).": "拿到一对“黑杰克”牌（即前两张牌均为“A”）",
    "having blue eyes.": "有着蓝色的眼睛。拥有 O 型负血型。",
    "having O-Negative blood.": "命中",
    "Hits": "不可能事件",
    "Impossible Events": "在100次投掷中，几乎可以保证（97%以上）连续出现至少5次正面！",
    "In 100 flips, you are almost guaranteed (97%+) to see a streak of at least 5 heads!": "可能的",
    "likely": "最长连胜",
    "Longest Streak": "更不可能的是",
    "More unlikely than": "最不可能发生的事件",
    "Most Unlikely Event": "非企鹅对话框",
    "Non-penguin Dialogs": "发生",
    "occurrence": "发生概率",
    "That is more unlikely than...": "比......更不可能",
    "The Bullseye": "靶心",
    "The Hot Streak": "炽热连串",
    "The length of the longest run of heads in n flips": "在 n 次抛硬币中连续出现正面的最长连串长度",
    "The n-th x-step Fibonacci number": "第 n 个 x 步斐波那契数",
    "The specific number of heads targeted": "所要达到的特定正面出现次数",
    "The target streak length": "目标连串长度",
    "Your absolute rarest": "您所经历的最罕见情况",
    "Unlock ???": "解锁 ???",
    "New": "新",
    "purple": "紫色",
    "Purple": "紫色",
    "PURPLE EVENT": "紫色事件",
    "Show": "显示",
    "just now": "刚刚",
    "Dismiss": "关闭",
    "Claim Reward": "领取奖励",
    "?! One percent or LESS?!": "？！概率只有百分之一甚至更低？！",
    "... being dealt 'Pocket Aces' in Texas Hold'Em.": "……在德州扑克中发到**一对口袋A**。",
    "Alternating": "交替出现",
    "being dealt 'Pocket Aces' in Texas Hold'Em.": "在德州扑克中发到**一对口袋A**。",
    "event for": "触发事件",
    "Hold on. HOLD ON. Did you just... did you ACTUALLY...": "等等。等一下！你刚才……你该不会真的……",
    "I need to sit down. No wait, I'm just an anonymous game narrator, I can't sit. I NEED TO CONCEPTUALLY SIT!": "我需要坐下。不对，我只是个匿名的游戏旁白，我没法坐下。我**需要在概念上坐下**！",
    "I'm just that good!": "我就是这么厉害！",
    "New Most Unlikely Event!": "全新最稀有事件！",
    "Stops on blue+ events & discoveries": "停留在蓝色及以上事件与发现",
    "You either have impeccable timing, or you've bribed the random number generator. Suspicious.": "你要么是时机精准到离谱，要么就是收买了随机数生成器。太可疑了。",
    "blue": "蓝色",
    "max": "最大",
    "\"x is a happy number in n coins\"": "\"x 是 n 枚硬币中的 快乐数\"",
    "\"x is a prime number in n coins\"": "\"x 是 n 枚硬币中的 质数\"",
    "Happy number": "快乐数",
    "Happy Count": "快乐数量",
    "Diamond (Every hit)": "钻石 (每次命中)",
    "Gold (Every hit)": "金币 (每次命中)",
    "Unlock a map to have some place to throw your darts...": "解锁地图后，就能找到一个可以投掷飞镖的地方了……",
    ". A number is happy if repeated sum of squared digits leads to 1.": "若一个数字的各位数字平方和经反复计算最终得到1，则该数字为**快乐数**。",
    ". Calculated using Exact Dynamic Programming.": "采用**精确动态规划法**计算。",
    "\"At least x alternating flips in n coins\"": "“抛n枚硬币，至少出现x次交替翻面”",
    "\"Longest palindrome of length x found in n coins\"": "“在n枚硬币结果中，找到长度恰好为x的最长回文序列”",
    "Alternating Pattern": "交替模式",
    "An alternating sequence (HTHT...) is mathematically equivalent to a run of identical results in the 'differences' between adjacent coins.": "交替序列（正-反-正-反……）在数学上等价于相邻硬币结果“差值”构成的连续相同序列。",
    "Calculates the probability that the heads count is a": "计算正面朝上次数为",
    "Calculates the probability that the longest substring of flips reading the same forwards and backwards is exactly length": "计算翻面结果中，正读和反读完全相同的最长子串长度恰好为",
    "Humans often think alternating sequences look 'more random' than streaks, but they are just as likely!": "人类常认为交替序列比连续序列“更随机”，但二者出现的概率其实完全相同！",
    "In base 10, the first few happy numbers are 1, 7, 10, 13, 19, 23, 28, 31, 32. The number 7 is the smallest happy number > 1!": "在十进制中，前几个快乐数为1、7、10、13、19、23、28、31、32。数字7是大于1的最小快乐数！",
    "Length of longest palindrome substring": "最长回文子串长度",
    "Longest run of heads in n-1 flips": "n-1次抛硬币中正面朝上的最长连续次数",
    "Palindrome Substring": "回文子串",
    "Target length": "目标长度",
    "The Grand Mirror": "宏伟镜像",
    "The Joyful Sum": "欢乐求和",
    "The length of the longest alternating sequence in n flips": "n次抛硬币中最长交替序列的长度",
    "The set of Happy Numbers": "快乐数集合",
    "The target alternating length": "目标交替长度",
    "The Zig-Zag": "之字形",
    "Total coins flipped": "抛硬币总次数",
    "Unlock a map to have some place to throw your darts...": "解锁一张地图，给你的飞镖找个投掷的地方……",
    "While any specific n-length palindrome is easier to get than n heads in a row, finding long palindromic substrings in random sequences is rare because most random patterns lack symmetry.": "尽管任意一个特定长度为n的回文序列，比连续n次正面朝上更容易出现，但在随机序列中找到长回文子串却十分罕见——因为大多数随机模式都缺乏对称性。",
    "... a man being color-blind.": "……男性色盲的概率。",
    "... a random person having autism.": "……随机一人患有自闭症的概率。",
    "... a random star in the Milky Way being 'Sun-like' (Class G).": "……银河系中随机一颗恒星为“类太阳恒星”（G型星）的概率。",
    "... being born a twin.": "……生来为双胞胎的概率。",
    "... having a third nipple (Polythelia).": "……拥有第三个乳头（多乳头症）的概率。",
    "... having naturally green eyes.": "……天生绿眼睛的概率。",
    "... having Spanish as your native language.": "……以西班牙语为母语的概率。",
    "... having Synesthesia (hearing colors, tasting shapes).": "……患有联觉症（听见颜色、品尝形状）的概率。",
    "... keeping a New Year's resolution for the entire year.": "……全年坚持完成新年决心的概率。",
    "... meeting a stranger who has your exact birthday.": "……遇到与你生日完全相同的陌生人的概率。",
    "Chance of getting at least x alternating flips": "至少出现x次交替翻面的概率",
    "Chance of the heads count being a Happy Number": "正面朝上次数为快乐数的概率",
    "Chance of the heads count being prime": "正面朝上次数为质数的概率",
    "Chance that the longest palindrome is exactly length x": "最长回文序列长度恰好为x的概率",
    "Dart Rewards": "飞镖奖励",
    "having a third nipple (Polythelia).": "拥有第三个乳头（多乳头症）。",
    "meeting a stranger who has your exact birthday.": "遇到与你生日完全相同的陌生人。",
    "Palindrome": "回文序列",
    "Prime Count": "质数次数",
    "Blue (First hit + Every 10th hit)": "蓝色（首次命中 + 每第10次命中）",
    "Impossible (Every hit)": "不可能（每次命中）",
    "Legendary (Every hit)": "传奇（每次命中）",
    "Purple (First hit + Every 2nd hit)": "紫色（首次命中 + 每第2次命中）",
    "Copy": "复制",
    "Contact": "联系",
    "Contact email:": "联系邮箱:",
    "Game version v": "游戏版本 v",
    "Current": "当前",
    "Email Other Feedback": "邮箱其他反馈",
    "Email Bug Report": "邮箱Bug上报",
    "Auto-Progress Alerts": "自动进度通知",
    "Export creates a compressed string to keep it shorter for transfer. Paste it on another device or browser to continue your progress, or keep it as a backup in case something happens. Import replaces your current save on this device.": "“导出”会生成一个压缩的字符串，以使其更短便于传输。将其粘贴到另一台设备或浏览器上，以便继续您的操作，或者将其保存为备份以防出现意外情况。 “导入”会覆盖您在此设备上的当前保存内容。",
    "OTHER:": "其他:",
    "Toggle": "切换",
    ". Since primes become rarer as numbers get larger, this probability generally decreases as n increases.": "。由于素数随着数字的增大而变得更为稀少，因此这一概率通常会随着n的增大而减小。",
    "Added 12 new formulas. 1 dice, 2 card, 2 D20, 5 roulette and 2 lottery formulas.": "新增了12个公式。其中包括1个骰子公式、2个卡片公式、2个D20公式、5个轮盘赌公式和2个彩票公式。",
    "Added a changelog.": "添加了更新日志。",
    "Added a new Animation Settings system with three modes: all enabled, selected enabled, and all disabled.": "新增了一个动画设置系统，该系统包含三种模式：全部启用、选定启用和全部禁用。",
    "Added parallel auto-play upgrades for Map and Planet mode, so Auto-Throw and Auto-Launch can keep running alongside other auto-play.": "为地图和行星模式增加了并行自动播放升级，因此自动投掷和自动发射可以与其他自动播放功能同时运行。",
    "Added per-mode animation controls in selected mode, including combined action+camera toggles for Dart and Rocket.": "在选定模式下增加了针对每种模式的动画控制，包括为飞镖和火箭添加动作+镜头切换的组合功能。",
    "Added stopped-tab ! indicators and clearer running/stopped auto-play messages.": "添加了停止标签！指示器以及更清晰的运行/停止自动播放消息。",
    "Adjusted the cost of auto-throw and auto-launch.": "调整了自动投掷和自动发射的成本。",
    "Alerts, controls and contact.": "警报、控制和联系。",
    "Aligned gas giant and ice giant kickback streak tracking with the Kickback Rewards table.": "根据“回扣奖励”表格，追踪对齐的气态巨行星和冰巨行星的回扣序列。",
    "All animations disabled": "所有动画已禁用",
    "All animations enabled": "所有动画已启用",
    "Calculates the probability that the total number of heads is a": "计算正面朝上的总数为a的概率",
    "Changed speed upgrades to use a percentage reduction per level instead of a static 50 ms each time.": "已将速度升级更改为每级按百分比减少，而非每次固定减少50毫秒。",
    "Choose how animations should behave.": "选择动画的行为方式。",
    "Fixed a case where Formula History could appear empty until switching formulas.": "修复了切换公式前公式历史记录可能显示为空的问题。",
    "Fixed auto-play rarity progression so higher-rarity discoveries also satisfy lower rarity unlock requirements.": "修复了自动播放稀有度提升机制，使得高稀有度的发现也能满足低稀有度解锁条件。",
    "Fixed Formula History efficiency so it uses attempts since a formula was unlocked, instead of all actions in the game mode.": "修复了公式历史效率的计算方式，使其使用自公式解锁以来的尝试次数，而非游戏模式中的所有操作次数。",
    "Fixed Nepal flag in overlay.": "修复了叠加层中的尼泊尔国旗问题。",
    "Fixed rocket chest dialog progress not being saved between sessions.": "修复了火箭箱对话进度在不同会话之间未保存的问题。",
    "Fixed rocket kickback rewards not being refunded to your rocket ammo.": "修复了火箭弹反冲奖励未退还给火箭弹弹药的问题。",
    "Fixed the High Numbers (25-49) lottery highlight so ball 25 now counts and highlights correctly.": "修复了“高数字（25-49）”彩票高亮显示的问题，现在球25能够正确计数和显示高亮。",
    "Fixed the Rocket Expert auto-play text to match its real stop condition.": "已修复火箭专家自动播放文本，使其与实际停止条件相匹配。",
    "for everything else.": "至于其他所有事情。",
    "for issues, or": "对于问题，或者",
    "Formatted Result, Best Action and Best All Action currency values with comma-separated numbers across game modes.": "格式化结果，游戏模式中最佳行动和最佳所有行动的货币值，数字之间用逗号分隔。",
    "Generate Export String": "生成导出字符串",
    "Greatly improved staircase probability calculation performance using an exact dynamic programming rewrite and cache hit path.": "通过精确的动态规划重写和缓存命中路径，显著提高了楼梯概率计算的性能。",
    "having Synesthesia (hearing colors, tasting shapes).": "有联觉（能听到颜色，能尝到形状）。",
    "Import and Replace Save": "导入并替换保存",
    "Improved Formula History number formatting and clarified that its payouts are shown before multipliers.": "改进了公式历史记录的编号格式，并明确了其赔付金额显示在乘数之前。",
    "Improved Happy Number probability performance with shared exact caching and faster happy-number evaluation.": "通过共享精确缓存和更快的快乐数评估，提高了快乐数概率性能。",
    "Improved roulette responsiveness when animations are disabled by deferring heavy finalize work and reducing high-frequency UI/storage update pressure.": "通过推迟繁重的 finalize 工作和减轻高频 UI/存储更新的压力，提高了禁用动画时轮盘赌的响应速度。",
    "Improved save export/import so large saves generate more reliably and transfer with shorter strings.": "改进了存档导出/导入功能，使大型存档的生成更加可靠，传输时字符串更短。",
    "Improved Solar System performance by automatically enabling movement-time asteroid/Kuiper culling only on low-FPS devices.": "通过仅在低帧率设备上自动启用移动时小行星/柯伊伯带天体剔除功能，提高了太阳系性能。",
    "Indicator of which tab is running and when auto-play has stopped.": "指示哪个标签页正在运行以及自动播放何时停止的指示器。",
    "Made it easier to click chests.": "使点击箱子变得更加容易。",
    "Make it possible to switch tabs while auto-play is active.": "在自动播放功能开启时，允许切换标签页。",
    "Moons now display their parent planet across all views: launch results, collection list, smallest object hit stats, and global stats modal.": "现在，在所有视图中，卫星都会显示其所属行星：发射结果、收藏列表、最小物体撞击统计数据以及全局统计数据模式。",
    "On touch devices, tapping a result card now highlights the matching items like hover does on desktop.": "在触控设备上，现在轻点结果卡片会像在桌面上悬停一样高亮显示匹配项。",
    "Plays a short tone when auto-progress is stopped by a threshold or by running out of resources.": "当自动进程因达到阈值或资源耗尽而停止时，会发出短促的提示音。",
    "Please start the email title with": "请在邮件标题中以以下内容开头",
    "Prime number": "素数",
    "Raised Rocket Speed costs to be more in line with Dart Speed costs.": "将火箭速度的成本提高，使其更接近飞镖速度的成本。",
    "Recent game updates by version.": "按版本分类的最新游戏更新。",
    "Reduced planet image sizes by 60%.": "星球图像尺寸缩小了60%。",
    "Reduced unnecessary UI work in Stats and Rocket mode to help prevent visible-tab performance slowdowns.": "在统计和火箭模式下减少了不必要的用户界面（UI）工作，以帮助防止可见标签页性能下降。",
    "Removed outdated staircase approximation wording in dice formula details.": "已删除骰子公式详情中过时的楼梯近似表述。",
    "Replaced blur-heavy translucent surfaces with more solid backgrounds across browsers to reduce UI choppiness.": "在各个浏览器中，用更实体的背景替换了模糊严重的半透明表面，以减少用户界面的卡顿感。",
    "Save Transfer": "保存转账",
    "Selected animations enabled": "已启用所选动画",
    "Shows a visual tab-title marker when auto-progress is stopped by a threshold or by running out of resources.": "当自动进度因达到阈值或资源耗尽而停止时，显示一个可视化的标签标题标记。",
    "Small currency display fixes.": "货币显示的小问题修复。",
    "Sound when auto-progress stops": "自动播放停止时的声音",
    "Tab title notification when auto-progress stops": "自动进度停止时的标签标题通知",
    "Tabs no longer disabled during auto-play.": "在自动播放期间，标签页不再被禁用。",
    "The Indivisible": "不可分割的",
    "The largest known prime (as of 2024) has 24 million+ digits! Primes are the 'atoms' of all other numbers.": "截至2024年，已知最大的素数有2400多万位！素数是所有其他数字的“原子”。",
    "The set of prime numbers {2, 3, 5, 7, ...}": "质数集合{2, 3, 5, 7, ...}",
    "Updated cooldown upgrade card text to simply say 'Reduces cooldown'.": "已更新冷却升级卡文本，简化为“减少冷却时间”。",
    "Updated staircase formula metadata text to match the real calculation semantics (at least length x).": "已更新楼梯公式元数据文本，以符合实际计算语义（至少长度为x）。",
    "Value Boost level in General stats.": "提升基础属性中的数值。",
    "Value Boost prices now grow more naturally instead of jumping too fast.": "价值提升 现在，价格增长更为自然，不会过快上涨。",
    "... getting into Harvard. (acceptance rates for applicants)": "...被哈佛大学录取。（申请人的录取率）",
    "getting into Harvard. (acceptance rates for applicants)": "进入哈佛大学。（申请人的录取率）",
    "Auto-Throw (Basic)": "自动投掷（基础）",
    "Behold! The World Map!": "请看！世界地图！",
    "Collection": "收藏",
    "Continents Visited": "已访问大洲",
    "Discover all 5 oceans": "发现全部5大洋",
    "Discovered Areas": "已探索区域",
    "Global Wealth": "全球财富",
    "Kickback Rewards": "反弹奖励",
    "Leaflet": "传单",
    "Let's throw stuff!": "让我们投掷东西吧！",
    "Parallel Auto-Throw": "并行自动投掷",
    "Remember those darts? Time to put them to use!": "还记得那些飞镖吗？是时候派上用场了！",
    "Throw": "投掷",
    "Throw darts at the map and discover the world. Every country and continent you hit gets logged. Can you discover them all?": "向地图投掷飞镖并探索世界。每击中一个国家和大洲都会被记录。你能全部发现吗？",
    "Tiles © Esri — National Geographic": "地块 © 埃斯里 — 国家地理",
    "having Spanish as your native language.": "以西班牙语为你的母语。",
    "... rolling 'Snake Eyes' (two 1s) on a pair of dice.": "...掷出一对骰子上的“蛇眼”（即两个 1 点）的结果。",
    "rolling 'Snake Eyes' (two 1s) on a pair of dice.": "掷出一对骰子上的“蛇眼”（即两个 1 点）的结果。",
    "…I said FUN fact. Stop rolling your eyes!": "“我再说一句有趣的事实。别再翻白眼了！",
    "Are you ready? Let's go on a vacation! This could be our big getaway! Just you, me, and whatever destination your dart happens to hit.": "”你准备好了吗？咱们去度假吧！这可能会是我们的一次长途旅行！就你、我，还有你投掷出去的任何目的地都行。",
    "Fun fact nobody ever mentions when doing this experiment:": "有趣的是，在做这个实验时从来没有人提及这一点：",
    "I'll try my best!": "我会尽我最大的努力！",
    "I'm hoping it lands us on a tropical paradise. A nice resort. Maybe a cabana with decent Wi-Fi?": "我希望它能把我们带到一个热带天堂。一个不错的度假胜地。也许是一个有良好网络信号的小木屋？",
    "No pressure! Take a deep breath and aim for the 29% land. I don't want a permanent swimming vacation!": "别太紧张！深吸一口气，瞄准那 29% 的陆地区域。我不想变成一个永远泡在水里的度假者！",
    "of Earth's surface is ocean!": "地球表面有 71% 是海洋！",
    "Area:": "区域:",
    "Area": "区域",
    "Country": "地区",
    "Throwing": "投掷中",
    "Small Area (< 100k km²)": "小区域 (< 100k km²)",
    "Ocean": "大洋",
    "New Discovery!": "新发现!",
    "Micro Area (< 100 km²)": "微型区域 (< 100 km²)",
    "Medium Area (< 1M km²)": "中等区域 (< 1M km²)",
    "Large Area (< 5M km²)": "大型区域 (< 5M km²)",
    "Tiny Area (< 1k km²)": "迷你区域 (< 1k km²)",
    "Very Small Area (< 10k km²)": "很小区域 (< 10k km²)",
    "Every 10th": "每10次",
    "Every 3rd": "每3次",
    "Fingers crossed!": "祈求好运吧！",
    "Give me a moment to consult my atlas, cross-reference the coordinates with local tourism reviews, and check the average humidity.": "让我花点时间查阅我的地图册，将坐标与当地的旅游评价进行比对，并查看平均湿度情况。",
    "hit": "命中",
    "hit (> 5M km²)": "命中 (> 5M km²)",
    "Hit #": "命中 #",
    "Hit probability:": "命中概率：",
    "I'll report back if it's beach-worthy!": "如果它适合海滩，我会回来报告的！",
    "New Smallest Area Hit!": "新的最小面积命中！",
    "Now, don't celebrate just yet. We might have landed in a parking lot, or the middle of a desert.": "现在，先不要庆祝。",
    "Prob:": "我们可能降落在一个停车场，或者沙漠中央。问题：",
    "Size:": "尺寸：",
    "TERRA FIRMA!": "陆地！",
    "You hit land! You actually hit the": "你着陆了！你实际上命中了",
    "*SPLOOSH*": "*扑通*",
    "Area Rewards": "区域奖励",
    "I'm not angry with you, just very, very disappointed!": "我没有生你的气，只是非常非常失望！",
    "Magnificent aiming skills... Let's go befriend some fish.": "精准的瞄准技巧……咱们去和一些鱼交朋友吧。",
    "Pacific Ocean": "太平洋",
    "Remember how I said 71% of the planet is water? Statistically, this was always the most likely outcome.": "还记得我之前说过地球表面 71% 的面积是水域吗？从数据来看，这一直是最有可能出现的结果。",
    "Sorry...": "抱歉......",
    "Well. You hit water.": "好吧。你撞到了水里。",
    "(expected)": "（预期）",
    "* Russia and Turkey are counted as Asia": "* 俄罗斯与土耳其计入亚洲",
    "% | Area:": "占比 | 区域：",
    "% undiscovered": "未探索占比",
    "a random person having autism.": "随机一人患有自闭症",
    "Africa": "非洲",
    "Antarctica": "南极洲",
    "Areas Unlocked": "已解锁区域",
    "Asia": "亚洲",
    "Chests Collected": "已收集宝箱",
    "Darts Earned": "已获得飞镖",
    "Darts Thrown": "已投掷飞镖",
    "Discovery Progress": "探索进度",
    "Earned Total": "总计获得",
    "Europe": "欧洲",
    "From Coins": "来自硬币",
    "From Kickback": "来自反弹",
    "HITS": "命中次数",
    "Hits Analysis": "命中分析",
    "Last 10 Throws": "最近10次投掷",
    "No discoveries yet. Tap eye to peek.": "暂无发现。点击眼睛查看。",
    "North America": "北美洲",
    "Ocean Hits": "海洋命中次数",
    "Oceania": "大洋洲",
    "Oceans": "大洋",
    "Smallest Area Hit": "命中的最小区域",
    "South America": "南美洲",
    "Southern Ocean": "南大洋",
    "Territories": "领地",
    "Territory Hits": "领地命中次数",
    "Total Areas": "总区域数",
    "Total Darts Thrown": "总投掷飞镖数",
    "Your smallest area hit so far": "你目前命中的最小区域",
    "Atlantic Ocean": "大西洋",
    "Accessibility and Performance": "可访问性与性能",
    "Choose which animation groups stay enabled.": "选择哪些动画组保持启用状态。",
    "Export string created. It now uses compression to keep the string shorter for sharing and backup.": "已创建导出字符串。现在它会使用压缩技术来缩短字符串长度，以便于共享和备份。",
    "Generating...": "生成中...",
    "Show animation subchoices": "显示动画子选项",
    "/action": "/动作",
    "ACTION #": "动作 #",
    "being born a twin.": "生为双胞胎。",
    "Formula History shows base formula payouts before multipliers.": "公式历史显示的是在乘数作用前的基础赔付金额。",
    "having naturally green eyes.": "天生拥有绿色眼睛。",
    "Most Unlikely Occurrence": "最不可能发生的事情",
    "times": "次数",
    "Times not triggered": "未触发次数",
    "Total earned": "累计获得",
    "Triggered": "触发的",
    "And": "并且",
    "for when you are ready to leave the earth!": "因为当你们准备好离开地球的时候！",
    "Good news! A": "好消息!一个",
    "is now in effect.": "现在的效果。",
    "Kickback Program": "回扣计划",
    "rockets": "火箭",
    "Rockets": "火箭",
    "See that": "看这个",
    "Sudan": "苏丹",
    "table floating above the Throw button?": "桌子漂浮在投掷按钮上方？",
    "Throwing darts isn't just about geography. It's a business opportunity! You have a chance to win some darts back on every throw.": "投掷飞镖可不只是关于地理知识的事。这还是一门商业机会！每次投掷，你都有机会赢回一些飞镖。",
    "Understood!": "明白了！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "km²": "km²",
    "Arctic Ocean": "北冰洋",
    "China": "中国",
    "BUG:": "BUG:",
    "gameofchanceinc@gmail.com": "gameofchanceinc@gmail.com",
    "P(X \\in \\mathcal{H}) = \\sum_{h \\in \\mathcal{H}, h \\leq n} P(X = h)": "P(X \\in \\mathcal{H}) = \\sum_{h \\in \\mathcal{H}, h \\leq n} P(X = h)",
    "P(X \\in \\mathbb{P}) = \\sum_{k \\in \\mathbb{P}, k \\leq n} P(X = k)": "P(X \\in \\mathbb{P}) = \\sum_{k \\in \\mathbb{P}, k \\leq n} P(X = k)",
    "P(L_{\\max} = x)": "P(L_{\\max} = x)",
    "P(A_n \\geq x) = P(L_{n-1} \\geq x-1)": "P(A_n \\geq x) = P(L_{n-1} \\geq x-1)",
    "L_{n-1}": "L_{n-1}",
    "L_{\\max}": "L_{\\max}",
    "\\mathcal{H}": "\\mathcal{H}",
    "\\mathbb{P}": "\\mathbb{P}",
    "A_n": "A_n",
    "P(X = x) = \\binom{n}{x} (0.5)^n": "P(X = x) = \\binom{n}{x} (0.5)^n",
    "P(L_n \\geq x) = 1 - \\frac{a_n^{(x)}}{2^n}": "P(L_n \\geq x) = 1 - \\frac{a_n^{(x)}}{2^n}",
    "L_n": "L_n",
    "a_n^{(x)}": "a_n^{(x)}",
    "P(X \\geq x) = \\sum_{k=x}^{n} \\binom{n}{k} (0.5)^n": "P(X \\geq x) = \\sum_{k=x}^{n} \\binom{n}{k} (0.5)^n",
    "casino": "赌场",
    "f(x)": "f(x)",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "∑": "∑",
    "≥": "≥",
    "⏳": "⏳",
    "📊": "📊",
    "= +": "= +",
    "×": "×",
    "🌍": "🌍",
    "🔒": "🔒",
    "🏆": "🏆",
    "• +": "• +",
    "−": "−",
    "%)": "%)",
    "∈": "∈",
    "≤": "≤",
    "•": "•",
    "▾": "▾",
    "": "",
    "": "",
    "": "",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "Coin Speed ": "硬币速度 ",
    "Unlock your first formula ": "解锁你的第一个公式 ",
    "Unlock coin formula ": "解锁硬币公式 ",
    "Purple Events": "紫色事件",
    "Legendary Events": "传说事件",
    "Golden Events": "全局事件",
    "Blue Events": "蓝色事件",
    "Diamond Events": "钻石事件",
    "Dart Speed": "飞镖速度",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " (Actual)": " (实际)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^ \(([\d\.]+)\/([\d\.]+)\)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^ \(\<([\d\.]+)\%\)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\/$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) in ([\d\.,]+)$/, '$1 / $2'],
    [/^Longest palindrome of length ([\d\.,]+) found in ([\d\.,]+) coins$/, '在 $2 次抛硬币结果中，找到长度为 $1 的最长回文序列'],
    [/^([\d\.,]+) coins$/, '$1 硬币'],
    [/^([\d\.,]+) coin$/, '$1 硬币'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) throws ago$/, '$1 次投掷之前'],
    [/^([\d\.,]+) flips ago$/, '$1 翻转前'],
    [/^([\d\.,]+) flip ago$/, '$1 翻转前'],
    [/^([\d\.,]+) is a prime number in ([\d\.,]+) coins$/, '$1 是 $2 枚硬币中的 质数'],
    [/^([\d\.,]+) is a happy number in ([\d\.,]+) coins$/, '$1 是 $2 枚硬币中的 快乐数'],
    [/^At least ([\d\.,]+) heads in a row in ([\d\.,]+) coins$/, '一行中的 $2 枚硬币至少出现 $1 次正面'],
    [/^At least ([\d\.,]+) alternating flips in ([\d\.,]+) coins$/, '$2 枚硬币至少出现 $1 次交替翻转'],
    [/^At least ([\d\.,]+) heads in ([\d\.,]+) coins$/, '$2 枚硬币至少出现 $1 次正面'],
    [/^Exactly ([\d\.,]+) heads in ([\d\.,]+) coins$/, '$2 枚硬币恰好出现 $1 次正面'],
    [/^at least ([\d\.,]+) heads in ([\d\.,]+) flip$/, '$2 次翻转至少出现 $1 次正面'],
    [/^Throw ([\d\.,]+) darts$/, '投掷 $1 飞镖'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);