/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "Welcome to": "欢迎来到",
    "Stats": "统计",
    "luck": "幸运",
    "Reduces cooldown": "减少冷却时间",
    "Store": "商店",
    "We reward": "我们奖励",
    "Great!": "太棒了!",
    "Game of Chance": "概率游戏",
    "Formulas": "公式",
    "Flip": "翻转",
    "Events": "事件",
    "Buy new coin": "购买新硬币",
    "Balance": "余额",
    "Add another coin.": "增加另一个硬币。",
    "A Game of Chance": "一个关于概率的游戏。",
    ", an absolutely penguin-free game. Most games reward skill, strategy and countless hours of practice... but here?": "这是一款绝对不含企鹅的游戏。大多数游戏都会奖励技能、策略和无数小时的练习……但是在这里呢？",
    "Greetings, future Probability Wizard!": "你好，未来的概率魔法师！",
    "In this game, we embark on a journey to witness the extraordinary. The rarer the event, the sweeter the reward. Let's get started!": "在这个游戏中，我们将踏上一段见证非凡之事的旅程。事件越罕见，奖励就越丰厚。让我们开始吧！",
    ". It has potential. Dreams. A": "它蕴藏着潜力，承载着梦想。",
    "\"Just a coin?\" you might say. But this isn't ANY coin. This is a": "“只是一枚硬币而已？”你或许会这么想。但这绝非普通的硬币。这是一个 ——",
    "(Developer note: It won't. A physics engine is too hard to implement.)": "（开发人员备注：做不到的。物理引擎太难实现了。）",
    "Behold! A": "请看！一个",
    "chance of being heads, and a": "它有正面朝上的概率，",
    "chance of disappointing you by being tails.": "也有让你失望的反面朝上概率。",
    "Click the button to flip it! Each flip is a journey into the unknown. Will it be heads? Will it be tails? Will it somehow land on its edge and defy physics?": "点击按钮抛掷它！每一次翻转，都是一场通往未知的旅程。会是正面？会是反面？还是会奇迹般地立在边缘，违背物理法则？",
    "COIN": "硬币",
    "Digital Probability Disc™": "数字概率盘",
    "Not impressed.": "没什么可惊艳的。",
    "chance =": "几率 =",
    "It's like a": "它就像一个",
    "Let's do it!": "让我们开始吧！",
    "Let's play!": "开始玩吧！",
    "lucky": "幸运",
    "math": "数学",
    "or": "或",
    "Results": "结果",
    "secret": "秘密",
    "Total: +": "总计: +",
    "UNLOCKED": "已解锁",
    "You did it!": "你做到了！",
    "You got": "你得到了",
    "You just need to be": "你只需要做到",
    "Great": "太棒了",
    "Got it!": "知道了！",
    "Flipping": "翻转中",
    "bigger": "大于",
    "At Least": "至少",
    "You survived the tutorial!": "你完成了教程！",
    "everything": "所有",
    "Extra Info": "附加信息",
    "fake internet money": "虚假网络货币",
    "feel smart": "感觉聪明",
    "Coin Value Boost": "硬币价值提升",
    "Message Template": "消息模板",
    "So... you understood": "所以……你明白了",
    "Increases value by x1.1 (stacks with previous boosts)": "增加价值 x1.1（与之前的增益叠加）",
    "How it works": "工作原理",
    "— 100% certainty. Even a rock could do it.": "——百分之百的确定性。就算是石头也能做到。",
    ", except you can't lose your life savings and nobody will stage an intervention!": "，只不过你不会因为搞砸这件事而失去毕生积蓄，而且也不会有人来干预阻止你！",
    ", you don't actually need to understand any of that math to be good at this game.": "，你其实根本不需要懂那些数学知识就能在这项游戏中表现出色。",
    "! Chase those events like they owe you money! Make those numbers get": "!像对待欠你钱的人那样去应对那些事情！让那些数字变得（变得）更好！",
    "! The formulas are just there to make you": "!这些公式的存在只是为了让你.......",
    ". This is often more useful than exact counts for determining 'success'.": "。这通常比精确的计数更有助于确定“成功”的程度。",
    "\"At least x heads in n coins\"": "“在 n 枚硬币中至少出现 x 次正面”",
    "According to our formula, you have been paid": "根据我们的公式，您已获得报酬",
    "An event's likelihood equals how much it generates:": "一个事件发生的可能性等于其产生的价值：",
    "Binomial distribution": "二项分布",
    "But maybe you expected more of this game? What if I told you that you could win": "但也许您期望这个游戏能有更高的胜算？如果我告诉您，您有可能获胜",
    "Calculates the probability of getting at least a certain number of heads, based on the": "根据一定的条件计算出至少获得一定数量正面的概率，基于",
    "for the trivially true": "对于显然成立的情况",
    "Good luck out there!": "祝您好运！",
    "Great, I understood everything": "太好了，我都明白了",
    "in exchange for looking at some": "交换条件是看一些",
    "Let's take a look at your first formula!": "让我们来看看你的第一个公式！",
    "likely •": "可能•",
    "mathematical safari": "数学探险",
    "Remember: The rarer the event, the sweeter the reward! Hunt those probabilities like a": "请记住：事件越罕见，奖励就越丰厚！像狩猎概率一样去寻找那些概率吧！",
    "Tails": "尾巴",
    "That's what they all say! But here's a little": "这就是他们所说的全部内容！但这里还有一个小知识点：",
    "The Majority Rule": "多数原则",
    "The minimum number of heads required": "所需的最少硬币数量",
    "The number of heads obtained": "实际获得的硬币数量",
    "The probability of getting at least 50% heads is always slightly more than 50% because it includes the exact 50/50 case.": "获得至少 50% 硬币正面朝上的概率总是略高于 50%，这是因为它包含了恰好 50/50 的情况。",
    "Thrilling!": "惊心动魄！",
    "Total number of coins flipped": "总共翻动的硬币数量",
    "Try to flip the coin to earn your first coins.": "试着翻动硬币以获得你的第一枚硬币。",
    "Unlock powerful coin formulas to earn more money.": "解锁强大的硬币公式以赚取更多金钱。",
    "Variables": "变量",
    "while the random number generator does all the work. It's the academic equivalent of nodding while the teacher talks.": "而随机数生成器则完成了所有的工作。这在学术界就相当于老师讲课时你只是点头附和而已。",
    "You are now a certified Probability Apprentice.": "你现在已成为一名正式的概率学徒了。",
    "Unlock powerful coin formulas to earn more money.": "解锁强大的金币公式以赚取更多金钱。",
    "Unlock map": "解锁地图",
    "New Games": "新游戏",
    "Boost: x": "提升: x",
    "Auto-Flip (Basic)": "自动翻转 (基础)",
    "Darts": "飞镖",
    "Discover a purple event": "发现一个紫色事件",
    "Discover unique blue events": "发现一个独特的蓝色事件",
    "/ action": "/ 动作",
    "📊 Overview": "📊 概览",
    "Coins": "硬币",
    "Coin": "硬币",
    "coin": "硬币",
    "Blue": "蓝色",
    "Best": "最佳",
    "Action": "动作",
    "Common": "普通",
    "Common Events": "普通事件",
    "Currency Spent": "花费货币",
    "Currency Earned": "赚取货币",
    "Earned": "已赚取",
    "Earnings": "赚取中",
    "Efficiency": "效率",
    "Efficiency Score": "效率分数",
    "General": "常规",
    "Formulas (": "公式 (",
    "Formula History": "公式历史",
    "Formulas Unlocked": "已解锁公式",
    "Last 10 actions": "最近 10 动作",
    "Lv.": "等级",
    "Playtime": "游戏时长",
    "Purchases": "购买",
    "s Owned": "已拥有",
    "Spent": "花费",
    "Unique": "独特",
    "Unlocked": "已解锁",
    "Total": "总计",
    "Total Actions": "总计动作",
    "Total Events": "总计事件",
    "Total Flip All Actions": "所有动作总计翻转",
    "Total Items Flipped": "总计翻转的物品",
    "Total Coins Flipped": "总计硬币翻转",
    "Value Boost Level": "价值提升等级",
    "... having O-Negative blood.": "...有o型阴性血。",
    "... having blue eyes.": "...有蓝色眼睛。",
    "... getting a blackjack (first two cards).": "...得到一个21点（前两张牌）。",
    "\"At least x heads in a row in n coins\"": "“在 n 枚硬币中，至少连续出现 x 次正面朝上”",
    "Global Stats": "全局统计",
    "Global Statistics": "全局统计",
    "Got it": "知道了",
    "\"Exactly x heads in n coins\"": "\“n枚硬币中正好有x个正面\”",
    "🏆 Top 3 Most Unlikely Events Discovered": "🏆发现的最不可能的3个事件",
    "Activity": "活动",
    "Best Flip All Action": "最佳翻转全动作",
    "Calculates the exact probability of getting a specific number of heads. This is the foundation of the": "这是计算找到至少长度为 x 的连续正面朝上的概率的基础。这使用了通用的",
    "Calculates the probability of finding a consecutive run of heads of at least length x. This uses a generalized": "计算找到连续出现至少长度为x的正面的概率",
    "Chance of getting at least x heads in a row": "连续得到至少x次正面的概率",
    "Chance of getting at least x heads in n coins": "n枚硬币中至少得到x次正面的概率",
    "Chance of getting exactly x heads in n coins": "n枚硬币中恰好得到x个正面的概率",
    "Combined progress across all game modes": "综合所有游戏模式的进度",
    "Discover a purple event": "发现一个紫色事件",
    "Discover unique blue events": "发现独特的蓝色事件",
    "Even if you expect 5 heads in 10 flips, the chance of getting exactly 5 is only about 24.6%!": "即使你期望在10次投掷中得到5次正面，恰好得到5次正面的几率也只有24.6%！",
    "Exact Count": "精确计数",
    "Fibonacci sequence": "斐波那契数列",
    "for exact calculation.": "为了精确计算。",
    "getting a blackjack (first two cards).": "拿到一对“黑杰克”牌（即前两张牌均为“A”）",
    "having blue eyes.": "有着蓝色的眼睛。拥有 O 型负血型。",
    "having O-Negative blood.": "命中",
    "Hits": "不可能事件",
    "Impossible Events": "在100次投掷中，几乎可以保证（97%以上）连续出现至少5次正面！",
    "In 100 flips, you are almost guaranteed (97%+) to see a streak of at least 5 heads!": "可能的",
    "likely": "最长连胜",
    "Longest Streak": "更不可能的是",
    "More unlikely than": "最不可能发生的事件",
    "Most Unlikely Event": "非企鹅对话框",
    "Non-penguin Dialogs": "发生",
    "occurrence": "发生概率",
    "That is more unlikely than...": "比......更不可能",
    "The Bullseye": "靶心",
    "The Hot Streak": "炽热连串",
    "The length of the longest run of heads in n flips": "在 n 次抛硬币中连续出现正面的最长连串长度",
    "The n-th x-step Fibonacci number": "第 n 个 x 步斐波那契数",
    "The specific number of heads targeted": "所要达到的特定正面出现次数",
    "The target streak length": "目标连串长度",
    "Your absolute rarest": "您所经历的最罕见情况",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "P(X = x) = \\binom{n}{x} (0.5)^n": "P(X = x) = \\binom{n}{x} (0.5)^n",
    "P(L_n \\geq x) = 1 - \\frac{a_n^{(x)}}{2^n}": "P(L_n \\geq x) = 1 - \\frac{a_n^{(x)}}{2^n}",
    "L_n": "L_n",
    "a_n^{(x)}": "a_n^{(x)}",
    "P(X \\geq x) = \\sum_{k=x}^{n} \\binom{n}{k} (0.5)^n": "P(X \\geq x) = \\sum_{k=x}^{n} \\binom{n}{k} (0.5)^n",
    "casino": "赌场",
    "f(x)": "f(x)",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "∑": "∑",
    "≥": "≥",
    "⏳": "⏳",
    "📊": "📊",
    "= +": "= +",
    "×": "×",
    "🌍": "🌍",
    "🔒": "🔒",
    "🏆": "🏆",
    "• +": "• +",
    "−": "−",
    "%)": "%)",
    "": "",
    "": "",
    "": "",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "Coin Speed ": "硬币速度 ",
    "Unlock your first formula ": "解锁你的第一个公式 ",
    "Unlock coin formula ": "解锁硬币公式 ",
    "Purple Events": "紫色事件",
    "Legendary Events": "传说事件",
    "Golden Events": "全局事件",
    "Blue Events": "蓝色事件",
    "Diamond Events": "钻石事件",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " (Actual)": " (实际)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^ \(\<([\d\.]+)\%\)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\/$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) in ([\d\.,]+)$/, '$1 / $2'],
    [/^([\d\.,]+) coins$/, '$1 硬币'],
    [/^([\d\.,]+) coin$/, '$1 硬币'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) flips ago$/, '$1 翻转前'],
    [/^([\d\.,]+) flip ago$/, '$1 翻转前'],
    [/^At least ([\d\.,]+) heads in a row in ([\d\.,]+) coins$/, '一行中的 $2 枚硬币至少出现 $1 次正面'],
    [/^At least ([\d\.,]+) alternating flips in ([\d\.,]+) coins$/, '$2 枚硬币至少出现 $1 次交替翻转'],
    [/^At least ([\d\.,]+) heads in ([\d\.,]+) coins$/, '$2 枚硬币至少出现 $1 次正面'],
    [/^Exactly ([\d\.,]+) heads in ([\d\.,]+) coins$/, '$2 枚硬币恰好出现 $1 次正面'],
    [/^at least ([\d\.,]+) heads in ([\d\.,]+) flip$/, '$2 次翻转至少出现 $1 次正面'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);